/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lab = IDL.Record({
  'id' : IDL.Nat,
  'contact' : IDL.Text,
  'name' : IDL.Text,
});
export const SubAccount = IDL.Record({
  'id' : IDL.Nat,
  'pin' : IDL.Text,
  'name' : IDL.Text,
  'labId' : IDL.Opt(IDL.Nat),
  'phone' : IDL.Text,
});
export const PathologyTest = IDL.Record({
  'id' : IDL.Nat,
  'mrp' : IDL.Float64,
  'name' : IDL.Text,
  'b2bRate' : IDL.Float64,
  'category' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'notes' : IDL.Text,
  'patientName' : IDL.Text,
  'testIds' : IDL.Vec(IDL.Nat),
  'paidAmount' : IDL.Float64,
  'subAccountId' : IDL.Nat,
  'dueAmount' : IDL.Float64,
});
export const SubAccountRate = IDL.Record({
  'b2bRate' : IDL.Float64,
  'testId' : IDL.Nat,
  'subAccountId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addPathologyTest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'addSampleData' : IDL.Func([], [], []),
  'addTransaction' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'adminLogout' : IDL.Func([], [], []),
  'createLab' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createSubAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'deleteLab' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deletePathologyTest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteSubAccount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteSubAccountTestRate' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllLabs' : IDL.Func([], [IDL.Vec(Lab)], ['query']),
  'getAllSubAccounts' : IDL.Func([IDL.Text], [IDL.Vec(SubAccount)], ['query']),
  'getAllTests' : IDL.Func([], [IDL.Vec(PathologyTest)], ['query']),
  'getAllTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], []),
  'getSubAccountById' : IDL.Func([IDL.Nat], [IDL.Opt(SubAccount)], ['query']),
  'getSubAccountRates' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SubAccountRate)],
      ['query'],
    ),
  'getSubAccountTransactions' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTotalSubAccountCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalTestCount' : IDL.Func([], [IDL.Nat], ['query']),
  'setSubAccountTestRate' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
  'updateLab' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updatePathologyTest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'updateSubAccount' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'updateTransactionPaid' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [], []),
  'verifySubAccountPin' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lab = IDL.Record({
    'id' : IDL.Nat,
    'contact' : IDL.Text,
    'name' : IDL.Text,
  });
  const SubAccount = IDL.Record({
    'id' : IDL.Nat,
    'pin' : IDL.Text,
    'name' : IDL.Text,
    'labId' : IDL.Opt(IDL.Nat),
    'phone' : IDL.Text,
  });
  const PathologyTest = IDL.Record({
    'id' : IDL.Nat,
    'mrp' : IDL.Float64,
    'name' : IDL.Text,
    'b2bRate' : IDL.Float64,
    'category' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'notes' : IDL.Text,
    'patientName' : IDL.Text,
    'testIds' : IDL.Vec(IDL.Nat),
    'paidAmount' : IDL.Float64,
    'subAccountId' : IDL.Nat,
    'dueAmount' : IDL.Float64,
  });
  const SubAccountRate = IDL.Record({
    'b2bRate' : IDL.Float64,
    'testId' : IDL.Nat,
    'subAccountId' : IDL.Nat,
  });
  
  return IDL.Service({
    'addPathologyTest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addSampleData' : IDL.Func([], [], []),
    'addTransaction' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'adminLogout' : IDL.Func([], [], []),
    'createLab' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createSubAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'deleteLab' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deletePathologyTest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteSubAccount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteSubAccountTestRate' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllLabs' : IDL.Func([], [IDL.Vec(Lab)], ['query']),
    'getAllSubAccounts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SubAccount)],
        ['query'],
      ),
    'getAllTests' : IDL.Func([], [IDL.Vec(PathologyTest)], ['query']),
    'getAllTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], []),
    'getSubAccountById' : IDL.Func([IDL.Nat], [IDL.Opt(SubAccount)], ['query']),
    'getSubAccountRates' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SubAccountRate)],
        ['query'],
      ),
    'getSubAccountTransactions' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTotalSubAccountCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalTestCount' : IDL.Func([], [IDL.Nat], ['query']),
    'setSubAccountTestRate' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'updateLab' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updatePathologyTest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updateSubAccount' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'updateTransactionPaid' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'verifySubAccountPin' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };