/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubAccount = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const PathologyTest = IDL.Record({
  'id' : IDL.Nat,
  'mrp' : IDL.Float64,
  'name' : IDL.Text,
  'b2bRate' : IDL.Float64,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPathologyTest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'addSampleData' : IDL.Func([], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'adminLogout' : IDL.Func([], [], []),
  'createSubAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deletePathologyTest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteSubAccount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllSubAccounts' : IDL.Func([IDL.Text], [IDL.Vec(SubAccount)], []),
  'getAllTests' : IDL.Func([], [IDL.Vec(PathologyTest)], ['query']),
  'getB2BTests' : IDL.Func([], [IDL.Vec(PathologyTest)], ['query']),
  'getTestByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PathologyTest)],
      ['query'],
    ),
  'getTotalSubAccountCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalTestCount' : IDL.Func([], [IDL.Nat], ['query']),
  'updatePathologyTest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubAccount = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const PathologyTest = IDL.Record({
    'id' : IDL.Nat,
    'mrp' : IDL.Float64,
    'name' : IDL.Text,
    'b2bRate' : IDL.Float64,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addPathologyTest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addSampleData' : IDL.Func([], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'adminLogout' : IDL.Func([], [], []),
    'createSubAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deletePathologyTest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteSubAccount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllSubAccounts' : IDL.Func([IDL.Text], [IDL.Vec(SubAccount)], []),
    'getAllTests' : IDL.Func([], [IDL.Vec(PathologyTest)], ['query']),
    'getB2BTests' : IDL.Func([], [IDL.Vec(PathologyTest)], ['query']),
    'getTestByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PathologyTest)],
        ['query'],
      ),
    'getTotalSubAccountCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalTestCount' : IDL.Func([], [IDL.Nat], ['query']),
    'updatePathologyTest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };