/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PathologyTest {
  'id' : bigint,
  'mrp' : number,
  'name' : string,
  'b2bRate' : number,
  'category' : string,
}
export interface SubAccount { 'id' : bigint, 'name' : string, 'phone' : string }
export interface SubAccountRate {
  'b2bRate' : number,
  'testId' : bigint,
  'subAccountId' : bigint,
}
export interface _SERVICE {
  'addPathologyTest' : ActorMethod<
    [string, string, string, number, number],
    bigint
  >,
  'addSampleData' : ActorMethod<[], undefined>,
  'adminLogin' : ActorMethod<[string, string], string>,
  'adminLogout' : ActorMethod<[], undefined>,
  'createSubAccount' : ActorMethod<[string, string, string], bigint>,
  'deletePathologyTest' : ActorMethod<[string, bigint], undefined>,
  'deleteSubAccount' : ActorMethod<[string, bigint], undefined>,
  'deleteSubAccountTestRate' : ActorMethod<[string, bigint, bigint], undefined>,
  'getAllSubAccounts' : ActorMethod<[string], Array<SubAccount>>,
  'getAllTests' : ActorMethod<[], Array<PathologyTest>>,
  'getB2BTests' : ActorMethod<[], Array<PathologyTest>>,
  'getSubAccountRates' : ActorMethod<[bigint], Array<SubAccountRate>>,
  'getTestByCategory' : ActorMethod<[string], Array<PathologyTest>>,
  'getTotalSubAccountCount' : ActorMethod<[], bigint>,
  'getTotalTestCount' : ActorMethod<[], bigint>,
  /**
   * / NEW FUNCTIONALITY
   */
  'setSubAccountTestRate' : ActorMethod<
    [string, bigint, bigint, number],
    undefined
  >,
  'updatePathologyTest' : ActorMethod<
    [string, bigint, string, string, number, number],
    undefined
  >,
  'updateSubAccount' : ActorMethod<[string, bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];