/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SubAccount {
    id: bigint;
    pin: string;
    name: string;
    labId?: bigint;
    phone: string;
}
export interface PathologyTest {
    id: bigint;
    mrp: number;
    name: string;
    b2bRate: number;
    category: string;
}
export interface Lab {
    id: bigint;
    contact: string;
    name: string;
}
export interface SubAccountRate {
    b2bRate: number;
    testId: bigint;
    subAccountId: bigint;
}
export interface Transaction {
    id: bigint;
    date: string;
    totalAmount: number;
    notes: string;
    patientName: string;
    testIds: Array<bigint>;
    paidAmount: number;
    subAccountId: bigint;
    dueAmount: number;
}
export interface backendInterface {
    addPathologyTest(sessionToken: string, name: string, category: string, mrp: number, b2bRate: number): Promise<bigint>;
    addSampleData(): Promise<void>;
    addTransaction(sessionToken: string, subAccountId: bigint, patientName: string, date: string, testIds: Array<bigint>, paidAmount: number, notes: string): Promise<bigint>;
    adminLogin(username: string, password: string): Promise<string>;
    adminLogout(): Promise<void>;
    createLab(sessionToken: string, name: string, contact: string): Promise<bigint>;
    createSubAccount(sessionToken: string, name: string, phone: string, pin: string, labId: bigint | null): Promise<bigint>;
    deleteLab(sessionToken: string, id: bigint): Promise<void>;
    deletePathologyTest(sessionToken: string, id: bigint): Promise<void>;
    deleteSubAccount(sessionToken: string, id: bigint): Promise<void>;
    deleteSubAccountTestRate(sessionToken: string, subAccountId: bigint, testId: bigint): Promise<void>;
    deleteTransaction(sessionToken: string, transactionId: bigint): Promise<void>;
    getAllLabs(): Promise<Array<Lab>>;
    getAllSubAccounts(sessionToken: string): Promise<Array<SubAccount>>;
    getAllTests(): Promise<Array<PathologyTest>>;
    getAllTransactions(sessionToken: string): Promise<Array<Transaction>>;
    getSubAccountById(subAccountId: bigint): Promise<SubAccount | null>;
    getSubAccountRates(subAccountId: bigint): Promise<Array<SubAccountRate>>;
    getSubAccountTransactions(subAccountId: bigint, pin: string): Promise<Array<Transaction>>;
    getTotalSubAccountCount(): Promise<bigint>;
    getTotalTestCount(): Promise<bigint>;
    setSubAccountTestRate(sessionToken: string, subAccountId: bigint, testId: bigint, b2bRate: number): Promise<void>;
    updateLab(sessionToken: string, id: bigint, name: string, contact: string): Promise<void>;
    updatePathologyTest(sessionToken: string, id: bigint, name: string, category: string, mrp: number, b2bRate: number): Promise<void>;
    updateSubAccount(sessionToken: string, id: bigint, name: string, phone: string, pin: string, labId: bigint | null): Promise<void>;
    updateTransactionPaid(sessionToken: string, transactionId: bigint, paidAmount: number): Promise<void>;
    verifySubAccountPin(subAccountId: bigint, pin: string): Promise<boolean>;
}
import type { SubAccount as _SubAccount } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPathologyTest(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPathologyTest(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPathologyTest(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSampleData();
            return result;
        }
    }
    async addTransaction(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: Array<bigint>, arg5: number, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async adminLogout(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout();
            return result;
        }
    }
    async createLab(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLab(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLab(arg0, arg1, arg2);
            return result;
        }
    }
    async createSubAccount(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubAccount(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubAccount(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deleteLab(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLab(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLab(arg0, arg1);
            return result;
        }
    }
    async deletePathologyTest(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePathologyTest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePathologyTest(arg0, arg1);
            return result;
        }
    }
    async deleteSubAccount(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubAccount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubAccount(arg0, arg1);
            return result;
        }
    }
    async deleteSubAccountTestRate(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubAccountTestRate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubAccountTestRate(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteTransaction(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0, arg1);
            return result;
        }
    }
    async getAllLabs(): Promise<Array<Lab>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLabs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLabs();
            return result;
        }
    }
    async getAllSubAccounts(arg0: string): Promise<Array<SubAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubAccounts(arg0);
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubAccounts(arg0);
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTests(): Promise<Array<PathologyTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTests();
            return result;
        }
    }
    async getAllTransactions(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions(arg0);
            return result;
        }
    }
    async getSubAccountById(arg0: bigint): Promise<SubAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubAccountById(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubAccountById(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubAccountRates(arg0: bigint): Promise<Array<SubAccountRate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubAccountRates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubAccountRates(arg0);
            return result;
        }
    }
    async getSubAccountTransactions(arg0: bigint, arg1: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubAccountTransactions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubAccountTransactions(arg0, arg1);
            return result;
        }
    }
    async getTotalSubAccountCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSubAccountCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSubAccountCount();
            return result;
        }
    }
    async getTotalTestCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalTestCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalTestCount();
            return result;
        }
    }
    async setSubAccountTestRate(arg0: string, arg1: bigint, arg2: bigint, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSubAccountTestRate(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSubAccountTestRate(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateLab(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLab(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLab(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updatePathologyTest(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: number, arg5: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePathologyTest(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePathologyTest(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateSubAccount(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubAccount(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubAccount(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateTransactionPaid(arg0: string, arg1: bigint, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransactionPaid(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransactionPaid(arg0, arg1, arg2);
            return result;
        }
    }
    async verifySubAccountPin(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifySubAccountPin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifySubAccountPin(arg0, arg1);
            return result;
        }
    }
}
function from_candid_SubAccount_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubAccount): SubAccount {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubAccount]): SubAccount | null {
    return value.length === 0 ? null : from_candid_SubAccount_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    pin: string;
    name: string;
    labId: [] | [bigint];
    phone: string;
}): {
    id: bigint;
    pin: string;
    name: string;
    labId?: bigint;
    phone: string;
} {
    return {
        id: value.id,
        pin: value.pin,
        name: value.name,
        labId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.labId)),
        phone: value.phone
    };
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubAccount>): Array<SubAccount> {
    return value.map((x)=>from_candid_SubAccount_n3(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
